name: CI Build and Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create env file
      run: |
        touch .env
        echo PORT=${{ secrets.PORT }} >> .env
        echo ADMIN_HASH=${{ secrets.ADMIN_HASH }} >> .env
        echo CDSI_HASH=${{ secrets.CDSI_HASH }} >> .env
        echo MEEF_HASH=${{ secrets.MEEF_HASH }} >> .env
        echo TNSID_HASH=${{ secrets.TNSID_HASH }} >> .env
        echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
        echo CDSI_USERNAME=${{ secrets.CDSI_USERNAME }} >> .env
        echo CDSI_PASSWORD=${{ secrets.CDSI_PASSWORD }} >> .env
        echo MEEF_USERNAME=${{ secrets.MEEF_USERNAME }} >> .env
        echo MEEF_PASSWORD=${{ secrets.MEEF_PASSWORD }} >> .env
        echo TNSID_USERNAME=${{ secrets.TNSID_USERNAME }} >> .env
        echo TNSID_PASSWORD=${{ secrets.TNSID_PASSWORD }} >> .env
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: "16"
        cache: 'npm'
    - name: "Installing dependencies"
      run: npm ci
    - name: "Building"
      run: npm run build --if-present
    - name: "Running tests"
      run: npm test
  
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          clean: false
      - name: "Installing dependencies"
        run: npm ci
      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@master"
        with:
          skip-tag: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Building"
        run: npm run build --if-present
      - name: "Restart PM2"
        run: pm2 restart 0
